from ddgs import DDGS
import ollama

MODEL = "llama3.1:8b"


def search_and_summarize(query: str, max_results: int = 7) -> str:
    """Searches the web for the given query and returns a short, direct
    spoken-style answer generated by the local LLM from the raw results."""

    try:
        results = list(DDGS().text(query, max_results=max_results))
    except Exception as e:
        return f"I couldn't search the web right now. Error: {e}"

    if not results:
        return f"I couldn't find anything about {query}."

    raw_context = ""
    for i, r in enumerate(results, start=1):
        title = r.get("title", "")
        body = r.get("body", "")
        raw_context += f"{i}. {title} — {body}\n"

    summary_prompt = f"""You are JARVIS, a voice assistant. Below are raw web search results for the query: "{query}"

{raw_context}

Give the direct answer in EXACTLY ONE short spoken sentence. State it as fact if the results support it — do not hedge with phrases like "it seems", "however", "not specified", or "based on". If the results clearly state the answer anywhere, extract it confidently and say it plainly. Only say you don't know if NONE of the results mention it at all.
No markdown, no bullet points, no second sentence.
"""

    response = ollama.chat(
        model=MODEL,
        messages=[{"role": "user", "content": summary_prompt}]
    )

    return response["message"]["content"]