from ddgs import DDGS
import ollama

MODEL = "llama3.1:8b"


def search_and_summarize(query: str, max_results: int = 5) -> str:
    """Searches the web for the given query and returns a short spoken-style
    summary of the top results, generated by the local LLM."""

    try:
        results = list(DDGS().text(query, max_results=max_results))
    except Exception as e:
        return f"I couldn't search the web right now. Error: {e}"

    if not results:
        return f"I couldn't find anything about {query}."

    # Build a compact block of raw search snippets for the LLM to work from
    raw_context = ""
    for i, r in enumerate(results, start=1):
        title = r.get("title", "")
        body = r.get("body", "")
        raw_context += f"{i}. {title} — {body}\n"

    print("\n--- RAW SEARCH RESULTS ---")
    print(raw_context)
    print("--- END RAW RESULTS ---\n")

    summary_prompt = f"""You are JARVIS, a voice assistant. Below are raw web search results for the query: "{query}"

{raw_context}

Answer in EXACTLY 1-2 short sentences, as if speaking out loud. Be direct — give the answer first, no preamble like "I found" or "based on the results."
If the results don't clearly contain the answer, say so in one short sentence — don't speculate or pad with extra context.
No markdown, no bullet points, no filler.
"""

    response = ollama.chat(
        model=MODEL,
        messages=[{"role": "user", "content": summary_prompt}]
    )

    return response["message"]["content"]